servers:
  - id: imalweb
    name: IMAL Web
    api_url_env: IMALWEB_API_URL
    ssh_host_env: IMALWEB_SSH_HOST
    ssh_port: 22
    ssh_username_env: IMALWEB_SSH_USERNAME

    application_control:
      enabled: false

  - id: node1
    name: Node 1
    api_url_env: NODE1_API_URL
    ssh_host_env: NODE1_SSH_HOST
    ssh_port: 22
    ssh_username_env: NODE1_SSH_USERNAME

    application_control:
      enabled: true
      tomcat_home: "/imal/TomcatNode1"
      process_match: "Dcatalina.base=/imal/TomcatNode1"
      shutdown_timeout: 30
      startup_timeout: 60

  - id: node2
    name: Node 2
    api_url_env: NODE2_API_URL
    ssh_host_env: NODE2_SSH_HOST
    ssh_port: 22
    ssh_username_env: NODE2_SSH_USERNAME


    application_control:
      enabled: true
      tomcat_home: "/imal/TomcatNode2"
      process_match: "Dcatalina.base=/imal/TomcatNode2"
      shutdown_timeout: 30
      startup_timeout: 60

