servers:
  - id: imalweb
    name: IMAL Web
    api_url: "https://xxxxxxxx/weburl/getaccountDetails"
    ssh_host: "192.X.X.X"
    ssh_port: 22
    ssh_username: "monitoring_user"

  - id: node1
    name: Node 1
    api_url: "https://xxxxxxxx/weburl/getaccountDetails"
    ssh_host: "192.X.X.X"
    ssh_port: 22
    ssh_username: "monitoring_user"

  - id: node2
    name: Node 2
    api_url: "https://xxxxxxxx/weburl/getaccountDetails"
    ssh_host: "192.X.X.X"
    ssh_port: 22
    ssh_username: "monitoring_user"

    
