servers:
  - id: imalweb
    name: IMAL Web
    api_url: "https://imalweb.premierbank.ke/imal_core_pws/pathservices/rest/processGeneralAccounts/returnGeneralAccountDetails"
    ssh_host: "192.168.0.82"
    ssh_port: 22
    ssh_username: "root"

  - id: node1
    name: Node 1
    api_url: "https://192.168.0.81:8443/imal_core_pws/pathservices/rest/processGeneralAccounts/returnGeneralAccountDetails"
    ssh_host: "192.168.0.81"
    ssh_port: 22
    ssh_username: "imaljava"

  - id: node2
    name: Node 2
    api_url: "https://192.168.0.83:8443/imal_core_pws/pathservices/rest/processGeneralAccounts/returnGeneralAccountDetails"
    ssh_host: "192.168.0.83"
    ssh_port: 22
    ssh_username: "imaljava"

    